name: 'dbt_snowflake_monitoring_tests'
version: '1.0.0'
config-version: 2

profile: dbt_snowflake_monitoring

models:
  dbt_snowflake_monitoring:
    enabled: true

clean-targets:
  - target
  - dbt_packages

dispatch:
  - macro_namespace: dbt
    search_order:
      - dbt_snowflake_monitoring_tests
      - dbt_snowflake_monitoring
      - dbt

vars:
  account_locator: a09e1
